#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ADMIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$ADMIN_DIR/.." && pwd)"
DIST_DIR="$ADMIN_DIR/dist"

if [[ ! -f "$REPO_ROOT/package.json" ]]; then
  echo "[ace:deploy:hostgator] Must be run inside repo." >&2
  exit 1
fi

: "${ACE_API_BASE:?ACE_API_BASE is required (e.g. https://xxxx.execute-api.us-east-1.amazonaws.com)}"

echo "[ace:deploy:hostgator] Building ACE static assets..."
cd "$REPO_ROOT"
npm run ace:build

cat > "$DIST_DIR/config.js" <<EOF
/**
 * Generated by admin-editor/scripts/deploy-hostgator.sh
 */
window.__ACE_CONFIG__ = {
  apiBase: "${ACE_API_BASE}",
  authMode: "bearer"
};
EOF

cp "$ADMIN_DIR/deploy/.htaccess" "$DIST_DIR/.htaccess"
echo "[ace:deploy:hostgator] Wrote dist/config.js and copied .htaccess"

if [[ -z "${HOSTGATOR_HOST:-}" || -z "${HOSTGATOR_USER:-}" || -z "${HOSTGATOR_PASS:-}" || -z "${HOSTGATOR_PATH:-}" ]]; then
  echo "[ace:deploy:hostgator] HostGator env vars not fully set."
  echo "Set HOSTGATOR_HOST, HOSTGATOR_USER, HOSTGATOR_PASS, HOSTGATOR_PATH to upload automatically."
  echo "Manual upload fallback: copy files from $DIST_DIR to your hosting path."
  exit 0
fi

if ! command -v lftp >/dev/null 2>&1; then
  echo "[ace:deploy:hostgator] lftp is not installed."
  echo "Install (macOS): brew install lftp"
  echo "Manual upload fallback: upload $DIST_DIR/* to $HOSTGATOR_PATH over SFTP."
  exit 0
fi

echo "[ace:deploy:hostgator] Uploading via SFTP with lftp..."
lftp -u "$HOSTGATOR_USER","$HOSTGATOR_PASS" "sftp://$HOSTGATOR_HOST" <<EOF
set sftp:auto-confirm yes
mkdir -p "$HOSTGATOR_PATH"
mirror -R --verbose --delete "$DIST_DIR/" "$HOSTGATOR_PATH/"
bye
EOF

echo "[ace:deploy:hostgator] Deploy complete."
