/**
 * Admin Config Editor – local server.
 * GET /api/model, POST /api/validate, POST /api/save (auth + editor+).
 * Auth: cookie ace_sid, file-backed users, RBAC admin/manager/editor/reviewer.
 * Serves static files from admin-editor/public.
 */

import express from 'express'
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'
import cookieParser from 'cookie-parser'
import { loadModel } from './src/model'
import { validateModel, adminEditableModelSchema, saveRequestBodySchema } from './src/schema'
import { saveModel, saveModelDryRun } from './src/save'
import { requireAuth, requireAdmin, requireRoleValidateSave } from './src/auth-middleware'
import {
  handleLogin,
  handleLogout,
  handleMe,
  handleBootstrapAllowed,
  handleBootstrap
} from './src/auth-routes'
import {
  handleListUsers,
  handleCreateUser,
  handleUpdateUser
} from './src/users-routes'
import { createKbRouter } from './src/kb-routes'
import { appendAuditLine } from './src/audit'
import type { AuthLocals } from './src/auth-middleware'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const adminEditorDir = __dirname
const repoRoot = path.resolve(adminEditorDir, '..')
const backupRootDir = path.join(adminEditorDir, '.backups')
const dataDir = path.join(adminEditorDir, 'data')

const ACE_DEBUG = process.env.ACE_DEBUG === '1' || process.env.ACE_DEBUG === 'true'
const app = express()
app.use(express.json({ limit: '10mb' }))
app.use(cookieParser())

// In dev, prevent caching of main static assets so refresh always serves current files (avoids stale UI/blank page).
const NO_CACHE_PATHS = new Set(['/', '/index.html', '/app.js', '/styles.css', '/fonts.css'])
if (process.env.NODE_ENV !== 'production') {
  app.use((req, res, next) => {
    if (req.method === 'GET' && NO_CACHE_PATHS.has(req.path)) {
      res.setHeader('Cache-Control', 'no-store')
    }
    next()
  })
}

app.use(express.static(path.join(adminEditorDir, 'public')))

// ——— Build info (no auth) ———
// Reads build/build-info.json (generated by scripts/generate-build-info.ts). No caching so ACE shows current build.
app.get('/api/build-info', (_req, res) => {
  res.setHeader('Cache-Control', 'no-store')
  const buildInfoPath = path.resolve(repoRoot, 'build', 'build-info.json')
  try {
    console.log('[build-info] path:', buildInfoPath)
    console.log('[build-info] exists:', fs.existsSync(buildInfoPath))
    if (!fs.existsSync(buildInfoPath)) {
      res.status(404).json({ version: '', buildId: undefined, builtAt: undefined })
      return
    }
    const buildInfo = JSON.parse(fs.readFileSync(buildInfoPath, 'utf-8'))
    const version = typeof buildInfo.version === 'string' ? buildInfo.version : ''
    const buildId = typeof buildInfo.buildId === 'string' ? buildInfo.buildId : undefined
    const builtAt = typeof buildInfo.builtAt === 'string' ? buildInfo.builtAt : undefined
    res.json({ version, buildId, builtAt })
  } catch (err) {
    console.log('[build-info] error:', err?.message ?? String(err))
    res.status(404).json({ version: '', buildId: undefined, builtAt: undefined })
  }
})

// ——— Auth routes (no auth required) ———
app.get('/api/auth/bootstrap-allowed', (req, res) => {
  handleBootstrapAllowed(req, res, dataDir)
})
app.post('/api/auth/bootstrap', (req, res, next) => {
  handleBootstrap(req, res, dataDir).catch(next)
})
app.post('/api/auth/login', (req, res, next) => {
  handleLogin(req, res, dataDir).catch(next)
})
app.post('/api/auth/logout', handleLogout)

// ——— Auth: me (requires valid session) ———
app.get('/api/auth/me', requireAuth(dataDir), (req, res) => handleMe(req, res, dataDir))

// ——— Users CRUD (admin only) ———
app.get('/api/users', requireAuth(dataDir), requireAdmin, (req, res) => {
  handleListUsers(req, res, dataDir)
})
app.post('/api/users', requireAuth(dataDir), requireAdmin, (req, res, next) => {
  handleCreateUser(req, res, dataDir).catch(next)
})
app.patch('/api/users/:id', requireAuth(dataDir), requireAdmin, (req, res, next) => {
  handleUpdateUser(req, res, dataDir).catch(next)
})

// ——— KB: registry + CRUD (admin/manager/editor) ———
app.use('/api/kb', requireAuth(dataDir), requireRoleValidateSave, createKbRouter(repoRoot))

// ——— Model: GET requires auth ———
app.get('/api/model', requireAuth(dataDir), (_req, res) => {
  res.set('Cache-Control', 'no-store')
  try {
    const { model, meta } = loadModel(repoRoot)
    const validation = validateModel(model)
    res.json({
      model,
      meta: {
        repoRoot: meta.repoRoot,
        filePaths: meta.filePaths,
        lastModified: meta.lastModified,
        revision: meta.revision,
        files: meta.files
      },
      validation: {
        errors: validation.errors,
        warnings: validation.warnings
      }
    })
  } catch (err: any) {
    res.status(500).json({ error: err?.message ?? String(err) })
  }
})

/** Format Zod errors for ACE UX: resolve assistantsManifest.assistants[i].quickActions[j].* to assistantId/actionId. */
function formatSchemaErrorsForACE (body: unknown, zodError: { errors: Array<{ path: (string | number)[]; message: string }> }): string[] {
  const model = body && typeof body === 'object' && 'model' in body ? (body as { model: unknown }).model : body
  const assistants = model && typeof model === 'object' && model !== null && 'assistantsManifest' in model
    ? (model as { assistantsManifest?: { assistants?: Array<{ id?: string; quickActions?: Array<{ id?: string }> }> } }).assistantsManifest?.assistants
    : undefined
  const pathPrefix = body && typeof body === 'object' && 'model' in body ? ['model'] : []
  return zodError.errors.map((e) => {
    const path = e.path
    const rel = pathPrefix.length && path[0] === 'model' ? path.slice(1) : path
    if (Array.isArray(assistants) && rel[0] === 'assistantsManifest' && rel[1] === 'assistants' && typeof rel[2] === 'number') {
      const i = rel[2]
      const asst = assistants[i]
      const assistantId = asst?.id ?? String(i)
      if (rel[3] === 'quickActions' && typeof rel[4] === 'number') {
        const j = rel[4]
        const actionId = asst?.quickActions?.[j]?.id ?? `quickActions[${j}]`
        const field = rel[5] !== undefined ? String(rel[5]) : ''
        const msg = field ? `${field}: ${e.message}` : e.message
        return `${assistantId}/${actionId}: ${msg}`
      }
      if (rel[3] === 'instructionBlocks' && typeof rel[4] === 'number') {
        const blockIdx = rel[4]
        const field = rel[5] !== undefined ? String(rel[5]) : ''
        const msg = field ? `${field}: ${e.message}` : e.message
        return `${assistantId}/instructionBlocks[${blockIdx}]: ${msg}`
      }
    }
    return `${path.join('.')}: ${e.message}`
  })
}

// ——— Validate: admin/manager/editor (reviewer 403) ———
app.post('/api/validate', requireAuth(dataDir), requireRoleValidateSave, (req, res) => {
  try {
    const parsed = adminEditableModelSchema.safeParse(req.body)
    if (!parsed.success) {
      const errors = formatSchemaErrorsForACE(req.body, parsed.error)
      return res.status(400).json({ errors, warnings: [] })
    }
    const result = validateModel(parsed.data)
    res.json({ errors: result.errors, warnings: result.warnings })
  } catch (err: any) {
    res.status(500).json({ error: err?.message ?? String(err) })
  }
})

// ——— Save: admin/manager/editor (reviewer 403); audit on success ———
app.post('/api/save', requireAuth(dataDir), requireRoleValidateSave, (req, res) => {
  const dryRun = req.query.dryRun === '1' || req.query.dryRun === 'true'
  const auth = res.locals.auth as AuthLocals
  try {
    const parsed = saveRequestBodySchema.safeParse(req.body)
    if (!parsed.success) {
      const errors = formatSchemaErrorsForACE(req.body, parsed.error)
      return res.status(400).json({ errors, success: false })
    }
    const { meta: currentMeta } = loadModel(repoRoot)
    const clientRevision = parsed.data.meta.revision
    if (ACE_DEBUG) {
      const match = currentMeta.revision === clientRevision
      console.log('[ACE /api/save] start: clientRevisionLength=' + (typeof clientRevision === 'string' ? clientRevision.length : 0) + ', currentMeta.revisionLength=' + (typeof currentMeta.revision === 'string' ? currentMeta.revision.length : 0) + ', match=' + match)
    }
    if (currentMeta.revision !== clientRevision) {
      return res.status(409).json({
        error: 'Files changed since load; reload to avoid overwriting.',
        meta: {
          repoRoot: currentMeta.repoRoot,
          filePaths: currentMeta.filePaths,
          lastModified: currentMeta.lastModified,
          revision: currentMeta.revision,
          files: currentMeta.files
        }
      })
    }
    const m = parsed.data.model
    const toSave = {
      config: m.config,
      assistantsManifest: m.assistantsManifest,
      customKnowledge: m.customKnowledge,
      contentModelsRaw: m.contentModelsRaw,
      designSystemRegistries: m.designSystemRegistries
    }
    if (dryRun) {
      const summary = saveModelDryRun(toSave, currentMeta, backupRootDir)
      if (!summary.success) {
        return res.status(400).json(summary)
      }
      return res.json(summary)
    }
    const summary = saveModel(toSave, currentMeta, backupRootDir)
    if (!summary.success) {
      res.status(400).json(summary)
      return
    }
    const { meta: newMeta } = loadModel(repoRoot)
    if (ACE_DEBUG) {
      console.log('[ACE /api/save] 200: newMeta.revisionLength=' + (typeof newMeta.revision === 'string' ? newMeta.revision.length : 0))
    }
    appendAuditLine(dataDir, {
      timestamp: new Date().toISOString(),
      user: auth.username,
      action: 'save',
      resource: 'model',
      revisionBefore: clientRevision,
      revisionAfter: newMeta.revision,
      filesWritten: summary.filesWritten || [],
      dryRun: false
    })
    res.json({ ...summary, meta: newMeta })
  } catch (err: any) {
    res.status(500).json({
      success: false,
      filesWritten: [],
      backupsCreatedAt: '',
      backupRoot: '',
      generatorsRun: [],
      errors: [err?.message ?? String(err)],
      nextSteps: 'Ask an admin to run `npm run build` and then publish via the normal process.'
    })
  }
})

const PORT = process.env.ADMIN_EDITOR_PORT ? parseInt(process.env.ADMIN_EDITOR_PORT, 10) : 3333
app.listen(PORT, () => {
  console.log(`Admin Config Editor server at http://localhost:${PORT}`)
  console.log(`Repo root: ${repoRoot}`)
  console.log(`Data dir: ${dataDir}`)
  console.log('Endpoints: GET /api/model, POST /api/validate, POST /api/save; auth: /api/auth/*, users: /api/users (admin)')
})
