#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${1:-$SCRIPT_DIR/ace-env.env}"
DIST_DIR="$REPO_ROOT/admin-editor/dist"
OUTPUT_FILE="$DIST_DIR/config.js"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE" >&2
  echo "Copy deploy/ace-env.example.env to deploy/ace-env.env and fill in your values." >&2
  exit 1
fi

if [[ ! -d "$DIST_DIR" ]]; then
  echo "Missing ACE dist directory: $DIST_DIR" >&2
  echo "Run 'npm run ace:build' before writing config.js." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

ACE_API_BASE="${ACE_API_BASE:-}"
ACE_AUTH_MODE="${ACE_AUTH_MODE:-bearer}"

if [[ -z "$ACE_API_BASE" ]]; then
  echo "ACE_API_BASE is required in $ENV_FILE" >&2
  exit 1
fi

ACE_API_BASE="${ACE_API_BASE%/}"

if [[ "$ACE_AUTH_MODE" != "bearer" ]]; then
  echo "ACE_AUTH_MODE must be 'bearer' for hosted ACE deployments." >&2
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
/**
 * Generated by deploy/write-config-js.sh
 * Source env: $(basename "$ENV_FILE")
 */
window.__ACE_CONFIG__ = {
  apiBase: "${ACE_API_BASE}",
  authMode: "${ACE_AUTH_MODE}"
};
EOF

echo "Wrote $OUTPUT_FILE"
echo "  apiBase: $ACE_API_BASE"
echo "  authMode: $ACE_AUTH_MODE"
