// scripts/build-assistants.ts
/**
 * Per-assistant compile gate.
 *
 * Runs tsc --noEmit scoped to src/assistants/ (via tsconfig.assistants.json),
 * then groups any errors by assistant directory. Assistants with no errors get a fresh
 * {name}.generated.ts snapshot. Assistants with errors keep their
 * existing snapshot. Always assembles _registry.generated.ts from
 * all present snapshots.
 *
 * Run via: npx tsx scripts/build-assistants.ts
 */

import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'

const ROOT = path.resolve(__dirname, '..')
const ASSISTANTS_DIR = path.join(ROOT, 'src', 'assistants')
const ASSISTANTS_REL = 'src/assistants'

// ---------------------------------------------------------------------------
// Exported for testing
// ---------------------------------------------------------------------------

/**
 * Parse tsc --noEmit stdout and group error lines by assistant directory name.
 * Only errors whose file path starts with `assistantsRelDir/` are included.
 */
export function groupErrorsByAssistant(
  tscOutput: string,
  assistantsRelDir: string
): Record<string, string[]> {
  const result: Record<string, string[]> = {}
  const prefix = assistantsRelDir.replace(/\\/g, '/') + '/'
  for (const line of tscOutput.split('\n')) {
    const normalised = line.replace(/\\/g, '/')
    if (!normalised.startsWith(prefix)) continue
    // e.g. src/assistants/analytics/handler.ts(14,5): error TS...
    const after = normalised.slice(prefix.length)
    const slashIdx = after.indexOf('/')
    if (slashIdx === -1) continue
    const name = after.slice(0, slashIdx)
    result[name] = result[name] || []
    result[name].push(line)
  }
  return result
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function findAssistantDirs(): string[] {
  return fs.readdirSync(ASSISTANTS_DIR)
    .filter(entry => {
      const full = path.join(ASSISTANTS_DIR, entry)
      return (
        fs.statSync(full).isDirectory() &&
        fs.existsSync(path.join(full, 'index.ts'))
      )
    })
    .sort()
}

function runTscNoEmit(): string {
  try {
    execSync('npx tsc --noEmit --project tsconfig.assistants.json', {
      cwd: ROOT,
      stdio: 'pipe',
    })
    return ''
  } catch (e: any) {
    return (e.stdout?.toString() || '') + (e.stderr?.toString() || '')
  }
}

function writeGeneratedFile(assistantName: string, timestamp: string): void {
  const dir = path.join(ASSISTANTS_DIR, assistantName)
  const outPath = path.join(dir, `${assistantName}.generated.ts`)
  const content = [
    `// ${assistantName}.generated.ts — DO NOT EDIT`,
    `// Generated by scripts/build-assistants.ts`,
    `// Last type-validated: ${timestamp}`,
    ``,
    `export { default as ${assistantName}Module } from './index'`,
    ``,
  ].join('\n')
  fs.writeFileSync(outPath, content, 'utf-8')
}

function assembleRegistry(assistantNames: string[], timestamp: string): void {
  const outPath = path.join(ASSISTANTS_DIR, '_registry.generated.ts')
  const lines = [
    `// _registry.generated.ts — DO NOT EDIT`,
    `// Assembled by scripts/build-assistants.ts`,
    `// Last assembled: ${timestamp}`,
    `//`,
    `// Add new assistants here when they first pass validation.`,
    ``,
    ...assistantNames.map(
      name => `export { ${name}Module } from './${name}/${name}.generated'`
    ),
    ``,
  ]
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8')
}

function main() {
  const DIVIDER = '─'.repeat(53)
  console.log(`── build-assistants ${'─'.repeat(34)}`)

  const assistants = findAssistantDirs()
  if (assistants.length === 0) {
    console.log('No assistant directories found in src/assistants/')
    process.exit(0)
  }

  const tscOutput = runTscNoEmit()
  const errors = groupErrorsByAssistant(tscOutput, ASSISTANTS_REL)
  const timestamp = new Date().toISOString()

  const kept: string[] = []
  const registryNames: string[] = []

  for (const name of assistants) {
    const generatedPath = path.join(ASSISTANTS_DIR, name, `${name}.generated.ts`)
    const hasErrors = errors[name] !== undefined

    if (hasErrors) {
      const firstError = errors[name][0] || 'type error'
      console.log(`⚠ ${name.padEnd(18)} kept previous     ${firstError.split(': error ')[1]?.split(':')[0] || 'type error'}`)
      kept.push(name)
    } else {
      writeGeneratedFile(name, timestamp)
      console.log(`✓ ${name.padEnd(18)} updated`)
    }

    // Include in registry if a generated file exists (updated or previously created)
    if (fs.existsSync(generatedPath)) {
      registryNames.push(name)
    }
  }

  console.log(DIVIDER)

  if (kept.length > 0) {
    console.log(`⚠ ${kept.length} assistant(s) kept previous version: ${kept.join(', ')}`)
    for (const name of kept) {
      for (const errLine of (errors[name] || []).slice(0, 3)) {
        console.log(`  ${errLine}`)
      }
    }
  }

  assembleRegistry(registryNames, timestamp)
  console.log(`Registry assembled (${registryNames.length} assistant(s)). Proceeding with build.`)
  console.log(DIVIDER)
}

const isMain = process.argv[1] && (
  process.argv[1] === __filename ||
  process.argv[1].endsWith('build-assistants.ts') ||
  process.argv[1].endsWith('build-assistants.js')
)
if (isMain) main()
