#!/usr/bin/env node
/**
 * Generate build metadata for plugin and ACE.
 * - Reads version from package.json
 * - buildId = env BUILD_NUMBER or UTC timestamp YYYYMMDD-HHmmss
 * - builtAt = ISO 8601 UTC
 * - gitSha = short SHA if git available (optional)
 * - Writes build/build-info.json (ACE server reads this; commit this file so ACE has a value in dev)
 * - Writes src/generated/buildInfo.ts (plugin UI; do not commit, generated at build time)
 *
 * Cwd-independent: rootDir = parent of scripts/ so "npm run build" from any cwd works.
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, '..')
const pkgPath = path.join(rootDir, 'package.json')
const buildInfoJsonPath = path.resolve(rootDir, 'build', 'build-info.json')
const buildInfoTsPath = path.resolve(rootDir, 'src', 'generated', 'buildInfo.ts')
const buildDir = path.dirname(buildInfoJsonPath)

function getBuildId(): string {
  if (process.env.BUILD_NUMBER && process.env.BUILD_NUMBER.trim()) {
    return process.env.BUILD_NUMBER.trim()
  }
  const now = new Date()
  const y = now.getUTCFullYear()
  const m = String(now.getUTCMonth() + 1).padStart(2, '0')
  const d = String(now.getUTCDate()).padStart(2, '0')
  const h = String(now.getUTCHours()).padStart(2, '0')
  const min = String(now.getUTCMinutes()).padStart(2, '0')
  const s = String(now.getUTCSeconds()).padStart(2, '0')
  return `${y}${m}${d}-${h}${min}${s}`
}

function getBuiltAt(): string {
  return new Date().toISOString()
}

function getGitSha(): string | undefined {
  try {
    const sha = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim()
    return sha || undefined
  } catch {
    return undefined
  }
}

let version = ''
try {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))
  version = typeof pkg.version === 'string' ? pkg.version : ''
} catch {
  console.warn('[generate-build-info] Could not read package.json, using empty version')
}

const buildId = getBuildId()
const builtAt = getBuiltAt()
const gitSha = getGitSha()

const jsonPayload = {
  version,
  buildId,
  builtAt,
  ...(gitSha != null ? { gitSha } : {})
}

const tsContent = `/**
 * Generated Build Info
 * DO NOT EDIT — generated by scripts/generate-build-info.ts
 */

export const BUILD_VERSION = ${JSON.stringify(version)}
export const BUILD_ID = ${JSON.stringify(buildId)}
export const BUILT_AT = ${JSON.stringify(builtAt)}
${gitSha != null ? `export const GIT_SHA = ${JSON.stringify(gitSha)}` : 'export const GIT_SHA: string | undefined = undefined'}

/** Datadog RUM: false = never init in plugin (avoids browser-intake-datadoghq.com errors in sandbox). Set true only for non-plugin builds that need RUM. */
export const ENABLE_DD_RUM = false
`

const jsonContent = JSON.stringify(jsonPayload, null, 2)

if (!fs.existsSync(buildDir)) {
  fs.mkdirSync(buildDir, { recursive: true })
}
fs.writeFileSync(buildInfoJsonPath, jsonContent, 'utf-8')

const genDir = path.dirname(buildInfoTsPath)
if (!fs.existsSync(genDir)) {
  fs.mkdirSync(genDir, { recursive: true })
}
fs.writeFileSync(buildInfoTsPath, tsContent, 'utf-8')

console.log('[generate-build-info] Wrote', buildInfoJsonPath, 'and', buildInfoTsPath)
