#!/usr/bin/env node
/**
 * Custom Overlay Generator
 * 
 * Reads /custom/config.json and /custom/knowledge/*.md files and generates
 * TypeScript modules that embed the custom configuration and knowledge bases.
 * 
 * Run as: npm run generate-custom-overlay or as part of build process
 */

import * as fs from 'fs'
import * as path from 'path'

interface CustomConfig {
  ui?: {
    hideContentMvpMode?: boolean
  }
  llm?: {
    endpoint?: string
    hideModelSettings?: boolean
  }
  knowledgeBases?: Record<string, {
    policy: 'append' | 'override'
    file: string
  }>
  networkAccess?: {
    baseAllowedDomains?: string[]
    extraAllowedDomains?: string[]
  }
  designSystems?: {
    enabled?: boolean
    activeRegistries?: string[]
    allowlist?: string[]
    denylist?: string[]
    strictMode?: boolean
  }
  analytics?: {
    enabled?: boolean
    endpointUrl?: string
    flushIntervalMs?: number
    maxBatchSize?: number
    maxBuffer?: number
    retryMaxAttempts?: number
    retryBaseDelayMs?: number
    debug?: boolean
  }
}

/**
 * Load custom config from /custom/config.json
 */
function loadCustomConfig(rootDir: string): CustomConfig | null {
  const configPath = path.join(rootDir, 'custom', 'config.json')
  try {
    if (!fs.existsSync(configPath)) {
      return null
    }
    const content = fs.readFileSync(configPath, 'utf-8')
    return JSON.parse(content) as CustomConfig
  } catch (error) {
    console.warn('[Custom Overlay] Error loading custom/config.json:', error)
    return null
  }
}

/**
 * Load custom knowledge bases from /custom/knowledge/*.md
 * Returns a record keyed by assistant ID (filename without .md extension)
 */
function loadCustomKnowledgeBases(rootDir: string): Record<string, string> {
  const knowledgeDir = path.join(rootDir, 'custom', 'knowledge')
  const knowledgeBases: Record<string, string> = {}
  
  if (!fs.existsSync(knowledgeDir)) {
    return {}
  }
  
  try {
    const files = fs.readdirSync(knowledgeDir)
    for (const file of files) {
      // Skip example files and README
      if (file.endsWith('.example.md') || file === 'README.md') {
        continue
      }
      if (file.endsWith('.md')) {
        const assistantId = file.replace('.md', '')
        const filePath = path.join(knowledgeDir, file)
        try {
          const content = fs.readFileSync(filePath, 'utf-8')
          knowledgeBases[assistantId] = content
        } catch (error) {
          console.warn(`[Custom Overlay] Failed to read ${filePath}:`, error)
        }
      }
    }
  } catch (error) {
    console.warn('[Custom Overlay] Error reading custom/knowledge directory:', error)
  }
  
  return knowledgeBases
}

/**
 * Load design system registries from /custom/design-systems/<id>/registry.json
 * Returns a record keyed by registry ID
 */
function loadDesignSystemRegistries(rootDir: string): Record<string, any> {
  const designSystemsDir = path.join(rootDir, 'custom', 'design-systems')
  const registries: Record<string, any> = {}
  
  if (!fs.existsSync(designSystemsDir)) {
    return {}
  }
  
  try {
    const entries = fs.readdirSync(designSystemsDir, { withFileTypes: true })
    for (const entry of entries) {
      // Only process directories (skip files like README.md)
      if (!entry.isDirectory()) {
        continue
      }
      
      const registryId = entry.name
      const registryJsonPath = path.join(designSystemsDir, registryId, 'registry.json')
      
      if (fs.existsSync(registryJsonPath)) {
        try {
          const content = fs.readFileSync(registryJsonPath, 'utf-8')
          const registry = JSON.parse(content)
          // Validate that it has required fields
          if (registry.id && registry.name && Array.isArray(registry.components)) {
            registries[registryId] = registry
          } else {
            console.warn(`[Custom Overlay] Invalid registry.json in ${registryId}: missing required fields`)
          }
        } catch (error) {
          console.warn(`[Custom Overlay] Failed to read/parse ${registryJsonPath}:`, error)
        }
      }
    }
  } catch (error) {
    console.warn('[Custom Overlay] Error reading custom/design-systems directory:', error)
  }
  
  return registries
}

/**
 * Generate custom config TypeScript module
 */
function generateConfigModule(config: CustomConfig | null): string {
  const configValue = config ? JSON.stringify(config, null, 2) : 'null'
  
  return `/**
 * Generated Custom Config
 * 
 * This file is auto-generated from /custom/config.json
 * DO NOT EDIT MANUALLY - edit /custom/config.json instead
 * 
 * Generated by scripts/generate-custom-overlay.ts
 */

export interface CustomConfig {
  ui?: {
    defaultMode?: 'content-mvp' | 'simple' | 'advanced'
    hideContentMvpMode?: boolean
  }
  llm?: {
    endpoint?: string
    hideModelSettings?: boolean
    uiMode?: 'full' | 'connection-only'
  }
  knowledgeBases?: Record<string, {
    policy: 'append' | 'override'
    file: string
  }>
  networkAccess?: {
    baseAllowedDomains?: string[]
    extraAllowedDomains?: string[]
  }
  resources?: {
    links?: {
      about?: { label: string; url: string }
      feedback?: { label: string; url: string }
      meetup?: { label: string; url: string }
    }
    credits?: {
      createdBy?: Array<{ label: string; url: string }>
      apiTeam?: Array<{ label: string; url: string }>
      llmInstruct?: Array<{ label: string; url: string }>
    }
  }
  designSystems?: {
    enabled?: boolean
    activeRegistries?: string[]
    allowlist?: string[]
    denylist?: string[]
    strictMode?: boolean
  }
  analytics?: {
    enabled?: boolean
    endpointUrl?: string
    flushIntervalMs?: number
    maxBatchSize?: number
    maxBuffer?: number
    retryMaxAttempts?: number
    retryBaseDelayMs?: number
    debug?: boolean
  }
}

export const customConfig: CustomConfig | null = ${configValue}
`
}

/**
 * Generate custom knowledge TypeScript module
 */
function generateKnowledgeModule(knowledgeBases: Record<string, string>): string {
  const knowledgeValue = JSON.stringify(knowledgeBases, null, 2)
  
  return `/**
 * Generated Custom Knowledge Bases
 * 
 * This file is auto-generated from /custom/knowledge/*.md
 * DO NOT EDIT MANUALLY - edit /custom/knowledge/*.md files instead
 * 
 * Generated by scripts/generate-custom-overlay.ts
 */

export const customKnowledgeByAssistant: Record<string, string> = ${knowledgeValue}
`
}

/**
 * Generate design system registries TypeScript module
 */
function generateRegistriesModule(registries: Record<string, any>): string {
  const registriesValue = JSON.stringify(registries, null, 2)
  
  return `/**
 * Generated Design System Registries
 * 
 * This file is auto-generated from /custom/design-systems/<id>/registry.json
 * DO NOT EDIT MANUALLY - edit /custom/design-systems/<id>/registry.json files instead
 * 
 * Generated by scripts/generate-custom-overlay.ts
 */

export const customDesignSystemRegistries: Record<string, any> = ${registriesValue}
`
}

/**
 * Main execution
 */
function main() {
  const rootDir = path.resolve(__dirname, '..')
  const configOutputPath = path.join(rootDir, 'src/custom/generated/customConfig.ts')
  const knowledgeOutputPath = path.join(rootDir, 'src/custom/generated/customKnowledge.ts')
  const registriesOutputPath = path.join(rootDir, 'src/custom/generated/customRegistries.ts')
  
  console.log('[Custom Overlay] Generating custom overlay modules...')
  
  const config = loadCustomConfig(rootDir)
  const knowledgeBases = loadCustomKnowledgeBases(rootDir)
  const registries = loadDesignSystemRegistries(rootDir)
  
  if (!config && Object.keys(knowledgeBases).length === 0 && Object.keys(registries).length === 0) {
    console.log('[Custom Overlay] No custom overlay found, generating empty modules')
  } else {
    console.log(`[Custom Overlay] Loaded custom config: ${config ? 'yes' : 'no'}`)
    console.log(`[Custom Overlay] Loaded ${Object.keys(knowledgeBases).length} knowledge base files`)
    console.log(`[Custom Overlay] Loaded ${Object.keys(registries).length} design system registries`)
  }
  
  const configCode = generateConfigModule(config)
  const knowledgeCode = generateKnowledgeModule(knowledgeBases)
  const registriesCode = generateRegistriesModule(registries)
  
  // Ensure generated directory exists
  const generatedDir = path.dirname(configOutputPath)
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true })
  }
  
  // Only write if content changed (like generate-presets.ts)
  let existingConfigContent = ''
  try {
    existingConfigContent = fs.readFileSync(configOutputPath, 'utf-8')
  } catch {
    // File doesn't exist yet
  }
  
  if (existingConfigContent === configCode) {
    console.log('[Custom Overlay] No changes detected in customConfig.ts, skipping write')
  } else {
    fs.writeFileSync(configOutputPath, configCode, 'utf-8')
    console.log(`[Custom Overlay] Generated: ${configOutputPath}`)
  }
  
  let existingKnowledgeContent = ''
  try {
    existingKnowledgeContent = fs.readFileSync(knowledgeOutputPath, 'utf-8')
  } catch {
    // File doesn't exist yet
  }
  
  if (existingKnowledgeContent === knowledgeCode) {
    console.log('[Custom Overlay] No changes detected in customKnowledge.ts, skipping write')
  } else {
    fs.writeFileSync(knowledgeOutputPath, knowledgeCode, 'utf-8')
    console.log(`[Custom Overlay] Generated: ${knowledgeOutputPath}`)
  }
  
  let existingRegistriesContent = ''
  try {
    existingRegistriesContent = fs.readFileSync(registriesOutputPath, 'utf-8')
  } catch {
    // File doesn't exist yet
  }
  
  if (existingRegistriesContent === registriesCode) {
    console.log('[Custom Overlay] No changes detected in customRegistries.ts, skipping write')
  } else {
    fs.writeFileSync(registriesOutputPath, registriesCode, 'utf-8')
    console.log(`[Custom Overlay] Generated: ${registriesOutputPath}`)
  }
  
  console.log('[Custom Overlay] ✓ Custom overlay generation complete')
}

main()
