#!/usr/bin/env node
/**
 * Custom Overlay Generator
 * 
 * Reads /custom/config.json and /custom/knowledge/*.md files and generates
 * TypeScript modules that embed the custom configuration and knowledge bases.
 * 
 * Run as: npm run generate-custom-overlay or as part of build process
 */

import * as fs from 'fs'
import * as path from 'path'

interface CustomConfig {
  ui?: {
    hideContentMvpMode?: boolean
  }
  llm?: {
    endpoint?: string
    hideModelSettings?: boolean
  }
  knowledgeBases?: Record<string, {
    policy: 'append' | 'override'
    file: string
  }>
}

/**
 * Load custom config from /custom/config.json
 */
function loadCustomConfig(rootDir: string): CustomConfig | null {
  const configPath = path.join(rootDir, 'custom', 'config.json')
  try {
    if (!fs.existsSync(configPath)) {
      return null
    }
    const content = fs.readFileSync(configPath, 'utf-8')
    return JSON.parse(content) as CustomConfig
  } catch (error) {
    console.warn('[Custom Overlay] Error loading custom/config.json:', error)
    return null
  }
}

/**
 * Load custom knowledge bases from /custom/knowledge/*.md
 * Returns a record keyed by assistant ID (filename without .md extension)
 */
function loadCustomKnowledgeBases(rootDir: string): Record<string, string> {
  const knowledgeDir = path.join(rootDir, 'custom', 'knowledge')
  const knowledgeBases: Record<string, string> = {}
  
  if (!fs.existsSync(knowledgeDir)) {
    return {}
  }
  
  try {
    const files = fs.readdirSync(knowledgeDir)
    for (const file of files) {
      // Skip example files and README
      if (file.endsWith('.example.md') || file === 'README.md') {
        continue
      }
      if (file.endsWith('.md')) {
        const assistantId = file.replace('.md', '')
        const filePath = path.join(knowledgeDir, file)
        try {
          const content = fs.readFileSync(filePath, 'utf-8')
          knowledgeBases[assistantId] = content
        } catch (error) {
          console.warn(`[Custom Overlay] Failed to read ${filePath}:`, error)
        }
      }
    }
  } catch (error) {
    console.warn('[Custom Overlay] Error reading custom/knowledge directory:', error)
  }
  
  return knowledgeBases
}

/**
 * Generate custom config TypeScript module
 */
function generateConfigModule(config: CustomConfig | null): string {
  const configValue = config ? JSON.stringify(config, null, 2) : 'null'
  
  return `/**
 * Generated Custom Config
 * 
 * This file is auto-generated from /custom/config.json
 * DO NOT EDIT MANUALLY - edit /custom/config.json instead
 * 
 * Generated by scripts/generate-custom-overlay.ts
 */

export interface CustomConfig {
  ui?: {
    hideContentMvpMode?: boolean
  }
  llm?: {
    endpoint?: string
    hideModelSettings?: boolean
  }
  knowledgeBases?: Record<string, {
    policy: 'append' | 'override'
    file: string
  }>
}

export const customConfig: CustomConfig | null = ${configValue}
`
}

/**
 * Generate custom knowledge TypeScript module
 */
function generateKnowledgeModule(knowledgeBases: Record<string, string>): string {
  const knowledgeValue = JSON.stringify(knowledgeBases, null, 2)
  
  return `/**
 * Generated Custom Knowledge Bases
 * 
 * This file is auto-generated from /custom/knowledge/*.md
 * DO NOT EDIT MANUALLY - edit /custom/knowledge/*.md files instead
 * 
 * Generated by scripts/generate-custom-overlay.ts
 */

export const customKnowledgeByAssistant: Record<string, string> = ${knowledgeValue}
`
}

/**
 * Main execution
 */
function main() {
  const rootDir = path.resolve(__dirname, '..')
  const configOutputPath = path.join(rootDir, 'src/custom/generated/customConfig.ts')
  const knowledgeOutputPath = path.join(rootDir, 'src/custom/generated/customKnowledge.ts')
  
  console.log('[Custom Overlay] Generating custom overlay modules...')
  
  const config = loadCustomConfig(rootDir)
  const knowledgeBases = loadCustomKnowledgeBases(rootDir)
  
  if (!config && Object.keys(knowledgeBases).length === 0) {
    console.log('[Custom Overlay] No custom overlay found, generating empty modules')
  } else {
    console.log(`[Custom Overlay] Loaded custom config: ${config ? 'yes' : 'no'}`)
    console.log(`[Custom Overlay] Loaded ${Object.keys(knowledgeBases).length} knowledge base files`)
  }
  
  const configCode = generateConfigModule(config)
  const knowledgeCode = generateKnowledgeModule(knowledgeBases)
  
  // Ensure generated directory exists
  const generatedDir = path.dirname(configOutputPath)
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true })
  }
  
  // Only write if content changed (like generate-presets.ts)
  let existingConfigContent = ''
  try {
    existingConfigContent = fs.readFileSync(configOutputPath, 'utf-8')
  } catch {
    // File doesn't exist yet
  }
  
  if (existingConfigContent === configCode) {
    console.log('[Custom Overlay] No changes detected in customConfig.ts, skipping write')
  } else {
    fs.writeFileSync(configOutputPath, configCode, 'utf-8')
    console.log(`[Custom Overlay] Generated: ${configOutputPath}`)
  }
  
  let existingKnowledgeContent = ''
  try {
    existingKnowledgeContent = fs.readFileSync(knowledgeOutputPath, 'utf-8')
  } catch {
    // File doesn't exist yet
  }
  
  if (existingKnowledgeContent === knowledgeCode) {
    console.log('[Custom Overlay] No changes detected in customKnowledge.ts, skipping write')
  } else {
    fs.writeFileSync(knowledgeOutputPath, knowledgeCode, 'utf-8')
    console.log(`[Custom Overlay] Generated: ${knowledgeOutputPath}`)
  }
  
  console.log('[Custom Overlay] ✓ Custom overlay generation complete')
}

main()
