/**
 * HTML Prototype Renderer for Design Workshop Assistant
 *
 * Pure function: receives DesignSpecV1, returns a self-contained clickable prototype HTML string.
 * Single-file, no external runtime dependencies.
 * Fonts: Open Sans embedded as base64 @font-face when src/assets/fonts/ files are present
 * (generated by scripts/generate-font-face-css.ts at build time). Falls back to system
 * sans-serif with no external calls when font files are absent.
 * Jazz DS tokens applied via CSS custom properties.
 */

import type { DesignSpecV1, BlockSpec } from './types'
import { FONT_FACE_CSS } from '../../generated/fontFaceCSS'
import { isLikelyTicker, getTickerLogoDataUri, getTickerName } from './stockLogos'
import { getBrandLogoDataUri } from './brandLogos/index'

/** Returns the best available logo URI: real brand SVG > letter-avatar fallback */
function getLogoUri(ticker: string): string {
  return getBrandLogoDataUri(ticker) ?? getTickerLogoDataUri(ticker)
}

const JAZZ_CSS_VARS = `
  --jazz-primary: #005EB8;
  --jazz-primary-hover: #004692;
  --jazz-primary-active: #002F6C;
  --jazz-primary-subtle: rgba(0,94,184,0.08);
  --jazz-navy: #002F6C;
  --jazz-cta: #128842;
  --jazz-gain: #128842;
  --jazz-loss: #DA0B16;
  --jazz-text: #0F171F;
  --jazz-muted: #5B6C7B;
  --jazz-subdued: #85888A;
  --jazz-border: #E2E4E5;
  --jazz-surface: #FFFFFF;
  --jazz-surface0: #FFFFFF;
  --jazz-surface1: #F5F7F8;
  --jazz-surface2: #F1F1F0;
  --jazz-icon-bg: #E8F0FA;
  --jazz-error: #BF2155;
  --jazz-warning: #D56B01;
  --jazz-radius: 4px;
  --jazz-radius-pill: 8px;
  --jazz-font: "Open Sans", "Helvetica Neue", helvetica, arial, sans-serif;
  --jazz-shadow-sm: 0 2px 4px rgba(0,0,0,0.10);
  --jazz-shadow-md: 0 3px 10px rgba(0,0,0,0.20);
  --jazz-shadow-lg: 0 8px 24px rgba(0,0,0,0.40);
  --chart-area: #4A8FD4;
  --chart-seg1: #7B9E4B;
  --chart-seg2: #2E7E9E;
  --chart-seg3: #6B5B95;
  --chart-tooltip: #0F171F;
`

/**
 * Wireframe CSS vars — overrides Jazz tokens to match Figma wireframe renderer:
 * light gray background (#F8F8F8), white cards/inputs, green primary (#128842),
 * 12px radius, neutral grays, system font.
 */
const WIREFRAME_CSS_VARS = `
  --jazz-primary: #128842;
  --jazz-primary-hover: #0e6b34;
  --jazz-primary-active: #0a5229;
  --jazz-primary-subtle: rgba(18,136,66,0.08);
  --jazz-navy: #444444;
  --jazz-cta: #128842;
  --jazz-gain: #128842;
  --jazz-loss: #DA0B16;
  --jazz-text: #333333;
  --jazz-muted: #666666;
  --jazz-subdued: #999999;
  --jazz-border: #D1D1D1;
  --jazz-surface: #FFFFFF;
  --jazz-surface0: #FFFFFF;
  --jazz-surface1: #F8F8F8;
  --jazz-surface2: #F0F0F0;
  --jazz-icon-bg: #F0F0F0;
  --jazz-error: #DA0B16;
  --jazz-warning: #D56B01;
  --jazz-radius: 12px;
  --jazz-radius-pill: 20px;
  --jazz-font: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  --jazz-shadow-sm: 0 1px 3px rgba(0,0,0,0.08);
  --jazz-shadow-md: 0 2px 8px rgba(0,0,0,0.12);
  --jazz-shadow-lg: 0 8px 24px rgba(0,0,0,0.20);
  --chart-area: #4A8FD4;
  --chart-seg1: #7B9E4B;
  --chart-seg2: #2E7E9E;
  --chart-seg3: #6B5B95;
  --chart-tooltip: #333333;
`

/**
 * Additional CSS overrides for wireframe mode applied on top of the re-mapped vars.
 * Handles cases where Jazz-specific structural choices need neutralizing.
 */
const WIREFRAME_OVERRIDE_CSS = `
  /* Status and title bars use neutral grays */
  .status-bar { background: #444444; }
  .screen-title-bar { background: #555555; font-weight: 600; }

  /* Cards: no colored left accent border in wireframe */
  .block-card { border-left-width: 1px; border-left-color: var(--jazz-border); }

  /* Ticker symbol links use dark text not primary color */
  .block-watchlist-ticker { color: var(--jazz-text); }

  /* Secondary / tertiary buttons: neutral borders and dark gray text */
  .block-button.secondary {
    color: var(--jazz-text);
    border-color: var(--jazz-border);
  }
  .block-button.tertiary {
    color: var(--jazz-text);
    border-color: var(--jazz-border);
  }

  /* Handoff badge uses wireframe green */
  .handoff-badge--source { background: #128842; }
  .handoff-badge--ds { background: var(--jazz-surface2); color: var(--jazz-muted); border: 1px solid var(--jazz-border); }

  /* Metrics grid gain color stays green */
  .block-metrics-value.gain { color: var(--jazz-gain); }

  /* Chart period active pill */
  .block-chart-period-btn.active-period {
    background: rgba(18,136,66,0.08);
    border-color: var(--jazz-primary);
    color: var(--jazz-primary);
  }

  /* Image placeholder — light gray matching wireframe */
  .block-image { background: #E6E6E6; color: #999; }

  /* Tab bar active icon/label uses green */
  .tab-item.active .tab-item-label { color: var(--jazz-primary); }
`

const BASE_CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: var(--jazz-font);
    background: var(--jazz-surface1);
    color: var(--jazz-text);
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 40px 16px 80px;
  }

  /* ── Handoff summary card ── */
  .handoff-card {
    background: var(--jazz-surface0);
    border: 1px solid var(--jazz-border);
    border-radius: 8px;
    box-shadow: var(--jazz-shadow-sm);
    padding: 14px 18px 12px;
    margin-bottom: 24px;
    display: flex;
    flex-direction: column;
    gap: 6px;
    max-width: 700px;
    width: 100%;
  }
  .handoff-card-top {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    gap: 12px;
    flex-wrap: wrap;
  }
  .handoff-card-title {
    font-size: 14px;
    font-weight: 700;
    color: var(--jazz-text);
    letter-spacing: -0.01em;
  }
  .handoff-card-badges {
    display: flex;
    gap: 6px;
    flex-wrap: wrap;
    align-items: center;
    flex-shrink: 0;
  }
  .handoff-badge {
    font-size: 10px;
    font-weight: 700;
    padding: 2px 8px;
    border-radius: 20px;
    letter-spacing: 0.02em;
    white-space: nowrap;
  }
  .handoff-badge--ds {
    background: var(--jazz-icon-bg);
    color: var(--jazz-primary);
  }
  .handoff-badge--screens {
    background: var(--jazz-surface1);
    color: var(--jazz-muted);
    border: 1px solid var(--jazz-border);
  }
  .handoff-badge--date {
    background: var(--jazz-surface1);
    color: var(--jazz-muted);
    border: 1px solid var(--jazz-border);
  }
  .handoff-badge--source {
    background: var(--jazz-primary);
    color: #fff;
  }
  .handoff-card-prompt {
    font-size: 11px;
    color: var(--jazz-subdued);
    font-style: italic;
    line-height: 1.5;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  /* ── Phone frame — fixed height so all screens are the same size ── */
  .phone-frame {
    width: 375px;
    height: 780px;
    display: flex;
    flex-direction: column;
    background: var(--jazz-surface);
    border-radius: 24px;
    box-shadow:
      0 0 0 1px rgba(0,0,0,0.08),
      var(--jazz-shadow-lg),
      var(--jazz-shadow-sm);
    overflow: hidden;
    flex-shrink: 0;
  }

  /* ── Status bar ── */
  .status-bar {
    background: var(--jazz-navy);
    padding: 10px 20px 8px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .status-bar-time {
    font-size: 12px;
    font-weight: 700;
    color: #ffffff;
  }
  .status-bar-icons {
    display: flex;
    gap: 6px;
    align-items: center;
  }
  .status-bar-icons span {
    font-size: 11px;
    color: rgba(255,255,255,0.85);
  }

  /* ── Screen title bar ── */
  .screen-title-bar {
    background: var(--jazz-primary);
    padding: 10px 20px;
    font-size: 13px;
    font-weight: 700;
    color: #ffffff;
    letter-spacing: 0.02em;
    min-height: 40px;
    display: flex;
    align-items: center;
  }

  /* ── Screen wrapper — fills remaining phone height, hidden unless active ── */
  .screen-wrapper { display: none; }
  .screen-wrapper.active {
    display: flex;
    flex-direction: column;
    flex: 1;
    overflow: hidden;
    min-height: 0;
  }

  /* ── Screen content — scrolls if blocks exceed phone height ── */
  .screen-content {
    display: flex;
    flex-direction: column;
    flex: 1;
    overflow-y: auto;
    min-height: 0;
  }

  /* ── Action buttons — pinned above tab bar ── */
  .screen-actions {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 12px 16px 14px;
    background: var(--jazz-surface);
    border-top: 1px solid var(--jazz-border);
    flex-shrink: 0;
  }
  .screen-actions .block-button { margin-bottom: 0; }

  /* ── Bottom tab bar ── */
  .tab-bar {
    display: flex;
    background: var(--jazz-surface);
    border-top: 1px solid var(--jazz-border);
    height: 56px;
    flex-shrink: 0;
  }
  .tab-item {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 2px;
    cursor: pointer;
    border: none;
    background: none;
    padding: 6px 0 8px;
    text-decoration: none;
  }
  .tab-item svg {
    width: 20px;
    height: 20px;
    flex-shrink: 0;
  }
  .tab-item-label {
    font-size: 9px;
    font-weight: 600;
    color: var(--jazz-muted);
    font-family: var(--jazz-font);
  }
  .tab-item.active .tab-item-label { color: var(--jazz-primary); }

  /* ── Block types ── */

  .block-heading {
    font-family: var(--jazz-font);
    color: var(--jazz-text);
    font-weight: 600;
    line-height: 1.25;
  }
  .block-heading.h1 { font-size: 26px; }
  .block-heading.h2 { font-size: 20px; }
  .block-heading.h3 { font-size: 16px; }

  .block-body-text {
    font-size: 15px;
    line-height: 1.55;
    color: var(--jazz-muted);
  }

  .block-button {
    display: block;
    width: 100%;
    font-family: var(--jazz-font);
    font-size: 15px;
    font-weight: 600;
    padding: 14px 16px;
    border-radius: var(--jazz-radius);
    border: none;
    cursor: pointer;
    text-align: center;
    text-decoration: none;
    transition: filter 0.12s ease;
    -webkit-appearance: none;
  }
  .block-button:hover { filter: brightness(0.94); }
  .block-button.primary {
    background: var(--jazz-cta);
    color: #ffffff;
  }
  .block-button.secondary {
    background: var(--jazz-surface);
    color: var(--jazz-primary);
    border: 1.5px solid var(--jazz-primary);
  }
  .block-button.tertiary {
    background: transparent;
    color: var(--jazz-muted);
    border: 1px solid var(--jazz-border);
  }

  .block-input-wrap {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }
  .block-input-label {
    font-size: 12px;
    font-weight: 600;
    color: var(--jazz-text);
    letter-spacing: 0.01em;
  }
  .block-input {
    font-family: var(--jazz-font);
    font-size: 15px;
    color: var(--jazz-text);
    background: var(--jazz-surface);
    border: 1.5px solid var(--jazz-border);
    border-radius: var(--jazz-radius);
    padding: 11px 14px;
    width: 100%;
    outline: none;
    transition: border-color 0.12s ease;
  }
  .block-input:focus { border-color: var(--jazz-primary); }
  .block-input::placeholder { color: var(--jazz-muted); }

  .block-card {
    background: var(--jazz-surface);
    border: 1px solid var(--jazz-border);
    border-left: 4px solid var(--jazz-primary);
    border-radius: var(--jazz-radius);
    padding: 14px 16px;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .block-card-label {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--jazz-muted);
  }
  .block-card-value {
    font-size: 20px;
    font-weight: 600;
    color: var(--jazz-text);
    line-height: 1.2;
  }

  .block-image {
    background: var(--jazz-icon-bg);
    border-radius: var(--jazz-radius);
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--jazz-muted);
    font-size: 12px;
    font-weight: 600;
  }

  /* ── Position card variant (ticker rows) ── */
  .block-card--position {
    flex-direction: row;
    align-items: center;
    gap: 12px;
    padding: 10px 14px;
    border-left: none;
    border-left-width: 1px;
  }
  .block-card--position .ticker-logo {
    width: 40px;
    height: 40px;
    border-radius: 8px;
    flex-shrink: 0;
    display: block;
  }
  .block-card--position .ticker-body {
    flex: 1;
    min-width: 0;
  }
  .block-card--position .ticker-symbol {
    font-size: 13px;
    font-weight: 700;
    color: var(--jazz-text);
    line-height: 1.3;
  }
  .block-card--position .ticker-name {
    font-size: 10px;
    color: var(--jazz-subdued);
    line-height: 1.2;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    margin-bottom: 1px;
  }
  .block-card--position .ticker-detail {
    font-size: 11px;
    color: var(--jazz-muted);
    line-height: 1.4;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .block-card--position .ticker-delta {
    font-size: 13px;
    font-weight: 700;
    white-space: nowrap;
    flex-shrink: 0;
    letter-spacing: -0.01em;
  }
  .delta-gain { color: var(--jazz-gain); }
  .delta-loss { color: var(--jazz-loss); }

  /* ── Metrics 2×2 grid block ── */
  .block-metrics-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    background: var(--jazz-surface);
    border: 1px solid var(--jazz-border);
    border-radius: var(--jazz-radius);
    overflow: hidden;
  }
  .block-metrics-cell {
    padding: 10px 14px;
    border-right: 1px solid var(--jazz-border);
    border-bottom: 1px solid var(--jazz-border);
  }
  .block-metrics-cell:nth-child(2n) { border-right: none; }
  .block-metrics-cell:nth-last-child(-n+2) { border-bottom: none; }
  .block-metrics-label {
    font-size: 10px;
    color: var(--jazz-muted);
    margin-bottom: 3px;
    line-height: 1.3;
  }
  .block-metrics-value {
    font-size: 13px;
    font-weight: 600;
    color: var(--jazz-text);
  }
  .block-metrics-value.gain { color: var(--jazz-gain); }

  /* ── Asset allocation block ── */
  .block-allocation {
    background: var(--jazz-surface);
    border: 1px solid var(--jazz-border);
    border-radius: var(--jazz-radius);
    padding: 10px 14px;
    display: flex;
    align-items: center;
    gap: 16px;
  }
  .block-allocation-donut { flex-shrink: 0; }
  .block-allocation-legend { flex: 1; display: flex; flex-direction: column; gap: 7px; }
  .block-alloc-row {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 12px;
  }
  .block-alloc-dot {
    width: 10px; height: 10px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .block-alloc-label { flex: 1; color: var(--jazz-muted); }
  .block-alloc-pct   { font-weight: 600; color: var(--jazz-text); }

  /* ── Watchlist block ── */
  .block-watchlist {
    background: var(--jazz-surface);
    border: 1px solid var(--jazz-border);
    border-radius: var(--jazz-radius);
    overflow: hidden;
  }
  .block-watchlist-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 14px 6px;
    border-bottom: 1px solid var(--jazz-border);
  }
  .block-watchlist-title {
    font-size: 12px;
    font-weight: 700;
    color: var(--jazz-text);
  }
  .block-watchlist-row {
    display: flex;
    align-items: center;
    padding: 8px 14px;
    border-bottom: 1px solid var(--jazz-border);
    gap: 10px;
  }
  .block-watchlist-row:last-child { border-bottom: none; }
  .block-watchlist-logo {
    width: 28px; height: 28px;
    border-radius: 14px;
    border: 1px solid var(--jazz-border);
    flex-shrink: 0;
    display: block;
  }
  .block-watchlist-ticker { font-size: 12px; font-weight: 700; color: var(--jazz-primary); flex: 1; }
  .block-watchlist-price  { font-size: 12px; color: var(--jazz-text); }
  .block-watchlist-chg    { font-size: 11px; font-weight: 600; min-width: 60px; text-align: right; }
  .block-watchlist-chg.gain { color: var(--jazz-gain); }
  .block-watchlist-chg.loss { color: var(--jazz-loss); }

  /* ── Portfolio chart block ── */
  .block-chart {
    background: var(--jazz-surface);
    border: 1px solid var(--jazz-border);
    border-radius: var(--jazz-radius);
    overflow: hidden;
  }
  .block-chart-period-row {
    display: flex;
    gap: 4px;
    padding: 8px 12px 4px;
  }
  .block-chart-period-btn {
    font-family: var(--jazz-font);
    font-size: 11px;
    font-weight: 600;
    padding: 3px 8px;
    border-radius: 20px;
    border: 1px solid var(--jazz-border);
    background: var(--jazz-surface);
    color: var(--jazz-muted);
    cursor: pointer;
  }
  .block-chart-period-btn.active-period {
    background: rgba(0,47,108,0.08);
    border-color: var(--jazz-primary);
    border-radius: var(--jazz-radius-pill);
    color: var(--jazz-primary);
  }
  .block-chart-svg { display: block; width: 100%; }
  .block-chart-caption {
    font-size: 10px;
    color: var(--jazz-muted);
    padding: 4px 12px 8px;
    text-align: right;
  }

  /* ── Navigation ── */
  .proto-nav {
    margin-top: 28px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;
    width: 375px;
  }

  .nav-dots {
    display: flex;
    gap: 8px;
    align-items: center;
  }
  .nav-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--jazz-border);
    cursor: pointer;
    transition: background 0.15s ease, transform 0.15s ease;
    border: none;
    padding: 0;
  }
  .nav-dot.active {
    background: var(--jazz-primary);
    transform: scale(1.3);
  }

  .nav-arrows {
    display: flex;
    align-items: center;
    gap: 32px;
  }
  .nav-arrow-btn {
    display: flex;
    align-items: center;
    gap: 6px;
    font-family: var(--jazz-font);
    font-size: 13px;
    font-weight: 600;
    color: var(--jazz-primary);
    background: none;
    border: none;
    cursor: pointer;
    padding: 6px 0;
    opacity: 1;
    transition: opacity 0.15s ease;
  }
  .nav-arrow-btn:disabled {
    color: var(--jazz-border);
    cursor: default;
  }
  .nav-screen-counter {
    font-size: 12px;
    font-weight: 600;
    color: var(--jazz-muted);
    min-width: 50px;
    text-align: center;
  }
`

const PANEL_CSS = `
  /* ── Workspace layout ── */
  .proto-workspace {
    display: flex;
    gap: 32px;
    align-items: flex-start;
  }

  .proto-left {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;
  }

  /* Move proto-nav inside proto-left so it renders below the phone */
  .proto-nav { margin-top: 0; }

  /* ── Double Diamond panel ── */
  .dd-panel {
    width: 260px;
    flex-shrink: 0;
    display: flex;
    flex-direction: column;
    gap: 4px;
    padding-top: 4px;
  }

  .dd-section {
    border-radius: 6px;
    overflow: hidden;
    border: 1px solid var(--jazz-border);
    background: var(--jazz-surface);
  }

  .dd-section-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 12px;
    cursor: pointer;
    user-select: none;
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--jazz-muted);
    background: var(--jazz-surface);
    border: none;
    width: 100%;
    text-align: left;
  }

  .dd-section-header:hover { background: var(--jazz-surface1); }

  .dd-section-header.active {
    background: var(--jazz-primary);
    color: #fff;
  }

  .dd-section-arrow {
    font-size: 10px;
    transition: transform 0.15s;
  }

  .dd-section-header.active .dd-section-arrow { transform: rotate(90deg); }

  .dd-section-body {
    display: none;
    padding: 8px 10px 10px;
    border-top: 1px solid var(--jazz-border);
    background: var(--jazz-surface);
  }

  .dd-section-body.open { display: flex; flex-direction: column; gap: 6px; }

  /* Panel action buttons */
  .dd-action {
    display: block;
    width: 100%;
    padding: 7px 10px;
    border-radius: var(--jazz-radius);
    font-size: 11px;
    font-weight: 600;
    cursor: pointer;
    border: none;
    text-align: left;
  }

  .dd-action-primary {
    background: var(--jazz-primary);
    color: #fff;
  }

  .dd-action-primary:hover { background: #0052a0; }

  .dd-action-secondary {
    background: var(--jazz-surface);
    color: var(--jazz-primary);
    border: 1px solid var(--jazz-primary) !important;
  }

  .dd-action-secondary:hover { background: var(--jazz-icon-bg); }

  .dd-action-ghost {
    background: var(--jazz-surface1);
    color: var(--jazz-muted);
    border: 1px solid var(--jazz-border) !important;
  }

  .dd-action-ghost:hover { background: #e8e8e8; }

  .dd-section-label {
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--jazz-muted);
    padding: 4px 2px 2px;
  }

  /* FPO badge shown inline when coming-soon item clicked */
  .fpo-badge {
    display: none;
    font-size: 9px;
    background: var(--jazz-icon-bg);
    color: var(--jazz-primary);
    border-radius: 10px;
    padding: 2px 7px;
    font-weight: 600;
    margin-left: 6px;
    vertical-align: middle;
    white-space: nowrap;
  }

  /* Coming-soon toast */
  .cs-toast {
    position: fixed;
    bottom: 24px;
    right: 24px;
    background: var(--jazz-navy);
    color: #fff;
    padding: 10px 16px;
    border-radius: 6px;
    font-size: 12px;
    font-weight: 600;
    opacity: 0;
    transform: translateY(8px);
    transition: opacity 0.2s, transform 0.2s;
    pointer-events: none;
    z-index: 100;
    max-width: 260px;
  }

  .cs-toast.show {
    opacity: 1;
    transform: translateY(0);
  }
`

const PANEL_HTML = `<aside class="dd-panel" aria-label="Design workflow panel">

  <!-- FPO-DEMO: Discover section -->
  <div class="dd-section" data-fpo="true">
    <button class="dd-section-header" onclick="toggleSection(this)" aria-expanded="false">
      <span>🔍 Discover</span>
      <span class="dd-section-arrow">▶</span>
    </button>
    <div class="dd-section-body">
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Accessibility / ADA review')">ADA Review <span class="fpo-badge">Coming soon</span></button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Design scorecard')">Scorecard <span class="fpo-badge">Coming soon</span></button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('UX heuristics review')">Heuristics <span class="fpo-badge">Coming soon</span></button>
    </div>
  </div>

  <!-- FPO-DEMO: Define section -->
  <div class="dd-section" data-fpo="true">
    <button class="dd-section-header" onclick="toggleSection(this)" aria-expanded="false">
      <span>🎯 Define</span>
      <span class="dd-section-arrow">▶</span>
    </button>
    <div class="dd-section-body">
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Problem framing')">Problem Statement <span class="fpo-badge">Coming soon</span></button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Jobs-to-be-done framing')">JTBD <span class="fpo-badge">Coming soon</span></button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Success metrics')">Metrics <span class="fpo-badge">Coming soon</span></button>
    </div>
  </div>

  <!-- Develop section — open by default -->
  <div class="dd-section">
    <button class="dd-section-header active" onclick="toggleSection(this)" aria-expanded="true">
      <span>⚡ Develop</span>
      <span class="dd-section-arrow">▶</span>
    </button>
    <div class="dd-section-body open">
      <button class="dd-action dd-action-primary" data-fpo="true" onclick="showComingSoon('Refine screens — adjust colours, copy and layout')">Refine screens →</button>
      <button class="dd-action dd-action-secondary" data-fpo="true" onclick="showComingSoon('Regenerate — create a fresh variation')">Regenerate</button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('New prompt — start from scratch')">New prompt</button>
      <div class="dd-section-label" style="margin-top:4px">Annotations</div>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Add review notes as Figma annotations')">Add review notes →</button>
    </div>
  </div>

  <!-- FPO-DEMO: Deliver section -->
  <div class="dd-section" data-fpo="true">
    <button class="dd-section-header" onclick="toggleSection(this)" aria-expanded="false">
      <span>🚀 Deliver</span>
      <span class="dd-section-arrow">▶</span>
    </button>
    <div class="dd-section-body">
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Send to code — generate HTML/CSS scaffold')">Send to code ✦</button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Generate Evergreen content table')">Evergreen table ✦</button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Generate analytics tagging table')">Analytics tagging ✦</button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Create Jira stories and acceptance criteria')">Jira stories ✦</button>
      <button class="dd-action dd-action-ghost" data-fpo="true" onclick="showComingSoon('Send to QA — create test scenarios')">QA checklist ✦</button>
    </div>
  </div>

  <p style="font-size:9px;color:var(--jazz-muted);margin-top:10px;padding:0 2px">✦ Coming soon &nbsp;·&nbsp; FPO items hidden in production</p>
</aside>`

const PANEL_JS = `
  // ── Double Diamond accordion ──
  function toggleSection(btn) {
    var body = btn.nextElementSibling;
    var isOpen = body.classList.contains('open');
    // Close all sections
    document.querySelectorAll('.dd-section-body').forEach(function(b) { b.classList.remove('open'); });
    document.querySelectorAll('.dd-section-header').forEach(function(h) {
      h.classList.remove('active');
      h.setAttribute('aria-expanded', 'false');
    });
    // Open clicked section if it was closed
    if (!isOpen) {
      body.classList.add('open');
      btn.classList.add('active');
      btn.setAttribute('aria-expanded', 'true');
    }
  }

  // ── Coming soon toast ──
  var _csTimer = null;
  function showComingSoon(label) {
    var toast = document.getElementById('cs-toast');
    if (!toast) return;
    toast.textContent = 'Coming soon: ' + label;
    toast.classList.add('show');
    if (_csTimer) clearTimeout(_csTimer);
    _csTimer = setTimeout(function() { toast.classList.remove('show'); }, 2500);
  }
`

const PROTOTYPE_JS = `
  var currentScreen = 0;

  function getScreens() {
    return document.querySelectorAll('.screen-wrapper');
  }
  function getDots() {
    return document.querySelectorAll('.nav-dot');
  }

  function goToScreen(n) {
    var screens = getScreens();
    var dots = getDots();
    var total = screens.length;
    var next = Math.max(0, Math.min(n, total - 1));
    if (next === currentScreen) return;
    screens[currentScreen].classList.remove('active');
    dots[currentScreen].classList.remove('active');
    currentScreen = next;
    screens[currentScreen].classList.add('active');
    dots[currentScreen].classList.add('active');
    updateNav();
  }

  function updateNav() {
    var screens = getScreens();
    var total = screens.length;
    var backBtn = document.getElementById('nav-back');
    var nextBtn = document.getElementById('nav-next');
    var counter = document.getElementById('nav-counter');
    backBtn.disabled = currentScreen === 0;
    nextBtn.disabled = currentScreen === total - 1;
    counter.textContent = (currentScreen + 1) + ' / ' + total;
  }

  document.addEventListener('DOMContentLoaded', function() {
    updateNav();

    // Primary buttons advance to next screen
    document.querySelectorAll('.block-button.primary').forEach(function(btn) {
      btn.addEventListener('click', function() {
        var screens = getScreens();
        if (currentScreen < screens.length - 1) {
          goToScreen(currentScreen + 1);
        }
      });
    });
  });
`

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function renderBlock(block: BlockSpec, gap: number): string {
  const mb = `margin-bottom:${gap}px`

  switch (block.type) {
    case 'heading': {
      const level = block.level ?? 1
      const tag = level === 1 ? 'h1' : level === 2 ? 'h2' : 'h3'
      return `<${tag} class="block-heading h${level}" style="${mb}">${escapeHtml(block.text)}</${tag}>`
    }

    case 'bodyText':
      return `<p class="block-body-text" style="${mb}">${escapeHtml(block.text)}</p>`

    case 'button': {
      const variant = block.variant ?? 'primary'
      return `<button class="block-button ${variant}" style="${mb}">${escapeHtml(block.text)}</button>`
    }

    case 'input': {
      const label = block.label ?? ''
      const placeholder = block.placeholder ?? ''
      const inputType = block.inputType ?? 'text'
      return `<div class="block-input-wrap" style="${mb}">
  <label class="block-input-label">${escapeHtml(label)}</label>
  <input class="block-input" type="${inputType}" placeholder="${escapeHtml(placeholder)}" />
</div>`
    }

    case 'card': {
      const cardTitle = block.title ?? ''
      const cardContent = block.content

      // Position card: ticker-style title (e.g. AAPL) → logo badge + colored delta
      if (isLikelyTicker(cardTitle)) {
        const logoUri = getLogoUri(cardTitle)
        // Parse content: "150 shares · $148.00 · +9.2%" — last ·-delimited segment starting with +/−
        const parts = cardContent.split('·').map(p => p.trim())
        const last = parts[parts.length - 1]
        const isDelta = last && (last.startsWith('+') || last.startsWith('−') || last.startsWith('-'))
        const delta = isDelta ? last : ''
        const detail = isDelta ? parts.slice(0, -1).join(' · ') : cardContent
        const deltaClass = delta.startsWith('+') ? 'delta-gain' : delta ? 'delta-loss' : ''
        const companyName = getTickerName(cardTitle)
        return `<div class="block-card block-card--position" style="${mb}">
  <img class="ticker-logo" src="${logoUri}" alt="${escapeHtml(cardTitle)}" width="40" height="40" />
  <div class="ticker-body">
    <div class="ticker-symbol">${escapeHtml(cardTitle)}</div>
    ${companyName ? `<div class="ticker-name">${escapeHtml(companyName)}</div>` : ''}
    <div class="ticker-detail">${escapeHtml(detail)}</div>
  </div>
  ${delta ? `<span class="ticker-delta ${deltaClass}">${escapeHtml(delta)}</span>` : ''}
</div>`
      }

      // Regular card — color the value if it starts with a delta sign
      const valueColor = cardContent.startsWith('+')
        ? ' style="color:var(--jazz-gain)"'
        : (cardContent.startsWith('−') || cardContent.startsWith('-'))
          ? ' style="color:var(--jazz-loss)"'
          : ''
      return `<div class="block-card" style="${mb}">
  <div class="block-card-label">${escapeHtml(cardTitle)}</div>
  <div class="block-card-value"${valueColor}>${escapeHtml(cardContent)}</div>
</div>`
    }

    case 'spacer':
      return `<div style="height:${block.height ?? 16}px;flex-shrink:0"></div>`

    case 'image': {
      const h = block.height ?? 80
      return `<div class="block-image" style="height:${h}px;${mb}">Image ${block.width ?? 100}×${h}</div>`
    }

    case 'chart': {
      // Static SVG area chart: Jazz DS confirmed tokens
      // YTD: Jan 2 $313,875 → Feb 18 peak $322,612 → Apr 2 $319,448
      const chartH = block.height ?? 140
      const caption = block.caption ?? ''
      const svgH = chartH - 20  // leave room for x-axis labels
      // Normalized Y positions (0=bottom $313k, 1.0=peak $323k)
      const yScale = (norm: number) => Math.round((svgH - 10) - norm * (svgH - 20))
      const yJan  = yScale(0.13)  // Jan 2: ~$313,875
      const yPeak = yScale(1.0)   // Feb 18: ~$322,612 (peak)
      const yApr  = yScale(0.64)  // Apr 2: $319,448
      const yMid  = yScale(0.60)  // early March
      const svgChart = `<svg viewBox="0 0 335 ${chartH}" xmlns="http://www.w3.org/2000/svg" class="block-chart-svg" aria-hidden="true">
  <defs>
    <linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#4A8FD4" stop-opacity="0.25"/>
      <stop offset="100%" stop-color="#4A8FD4" stop-opacity="0.02"/>
    </linearGradient>
  </defs>
  <!-- Y-axis labels -->
  <text x="4" y="14" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">$323k</text>
  <text x="4" y="${Math.round(svgH * 0.5) + 4}" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">$318k</text>
  <text x="4" y="${svgH - 6}" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">$313k</text>
  <!-- Grid lines -->
  <line x1="36" y1="12" x2="331" y2="12" stroke="#E2E4E5" stroke-width="1"/>
  <line x1="36" y1="${Math.round(svgH * 0.5)}" x2="331" y2="${Math.round(svgH * 0.5)}" stroke="#E2E4E5" stroke-width="1"/>
  <line x1="36" y1="${svgH - 10}" x2="331" y2="${svgH - 10}" stroke="#E2E4E5" stroke-width="1"/>
  <!-- Area fill -->
  <path d="M36,${yJan} C70,${yJan + 6} 90,${Math.round((yJan + yPeak) / 2)} 130,${yPeak} C160,${yPeak - 4} 180,${yPeak - 4} 210,${Math.round((yPeak + yMid) / 2)} C240,${yMid + 4} 270,${yMid + 4} 331,${yApr} L331,${svgH - 10} L36,${svgH - 10} Z" fill="url(#chartGrad)"/>
  <!-- Line -->
  <path d="M36,${yJan} C70,${yJan + 6} 90,${Math.round((yJan + yPeak) / 2)} 130,${yPeak} C160,${yPeak - 4} 180,${yPeak - 4} 210,${Math.round((yPeak + yMid) / 2)} C240,${yMid + 4} 270,${yMid + 4} 331,${yApr}" fill="none" stroke="#4A8FD4" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <!-- End dot -->
  <circle cx="331" cy="${yApr}" r="3.5" fill="#4A8FD4"/>
  <!-- Tooltip callout at end point -->
  <rect x="248" y="${yApr - 20}" width="80" height="16" rx="3" fill="#0F171F"/>
  <text x="288" y="${yApr - 9}" font-size="9" fill="#FFFFFF" text-anchor="middle" font-family="Open Sans,system-ui,sans-serif">Apr 2 · $319,448</text>
  <!-- Callout stem -->
  <line x1="331" y1="${yApr - 4}" x2="320" y2="${yApr - 4}" stroke="#0F171F" stroke-width="1"/>
  <!-- X-axis labels -->
  <text x="36"  y="${chartH}" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">Jan</text>
  <text x="118" y="${chartH}" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">Feb</text>
  <text x="200" y="${chartH}" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">Mar</text>
  <text x="310" y="${chartH}" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui,sans-serif">Apr</text>
</svg>`
      return `<div class="block-chart" style="${mb}">
  <div class="block-chart-period-row">
    <button class="block-chart-period-btn active-period">YTD</button>
    <button class="block-chart-period-btn">1M</button>
    <button class="block-chart-period-btn">3M</button>
    <button class="block-chart-period-btn">1Y</button>
    <button class="block-chart-period-btn">All</button>
  </div>
  ${svgChart}
  ${caption ? `<div class="block-chart-caption">${escapeHtml(caption)}</div>` : ''}
</div>`
    }

    case 'metricsGrid': {
      const cells = block.items.map(item => {
        const gainClass = item.gain ? ' gain' : ''
        return `<div class="block-metrics-cell">
  <div class="block-metrics-label">${escapeHtml(item.label)}</div>
  <div class="block-metrics-value${gainClass}">${escapeHtml(item.value)}</div>
</div>`
      }).join('\n')
      return `<div class="block-metrics-grid" style="${mb}">${cells}</div>`
    }

    case 'allocation': {
      // Donut SVG: r=34, stroke-width=20, cx=40, cy=40 → 80×80px
      // circumference = 2π*34 ≈ 213.6
      // stroke-dashoffset: C/4 starts at 12 o'clock; subtract cumulative arcs for subsequent segments
      const C = 213.6
      const eqDash  = (block.equity       / 100) * C
      const fiDash  = (block.fixedIncome  / 100) * C
      const altDash = (block.altAssets    / 100) * C
      const eqOffset  = 0
      const fiOffset  = C - eqDash
      const altOffset = C - eqDash - fiDash
      const total = block.total ?? '—'
      const donutSvg = `<svg width="80" height="80" viewBox="0 0 80 80" class="block-allocation-donut">
  <circle cx="40" cy="40" r="34" fill="none" stroke="#7B9E4B" stroke-width="20"
    stroke-dasharray="${eqDash.toFixed(1)} ${C.toFixed(1)}"
    stroke-dashoffset="${eqOffset.toFixed(1)}" transform="rotate(-90 40 40)"/>
  <circle cx="40" cy="40" r="34" fill="none" stroke="#2E7E9E" stroke-width="20"
    stroke-dasharray="${fiDash.toFixed(1)} ${C.toFixed(1)}"
    stroke-dashoffset="${fiOffset.toFixed(1)}" transform="rotate(-90 40 40)"/>
  <circle cx="40" cy="40" r="34" fill="none" stroke="#6B5B95" stroke-width="20"
    stroke-dasharray="${altDash.toFixed(1)} ${C.toFixed(1)}"
    stroke-dashoffset="${altOffset.toFixed(1)}" transform="rotate(-90 40 40)"/>
  <text x="40" y="37" text-anchor="middle" font-size="9" fill="#5B6C7B" font-family="Open Sans,system-ui">Total</text>
  <text x="40" y="48" text-anchor="middle" font-size="10" font-weight="600" fill="#0F171F" font-family="Open Sans,system-ui">${escapeHtml(total)}</text>
</svg>`
      return `<div class="block-allocation" style="${mb}">
  ${donutSvg}
  <div class="block-allocation-legend">
    <div class="block-alloc-row">
      <div class="block-alloc-dot" style="background:#7B9E4B"></div>
      <div class="block-alloc-label">Equity</div>
      <div class="block-alloc-pct">${block.equity.toFixed(2)}%</div>
    </div>
    <div class="block-alloc-row">
      <div class="block-alloc-dot" style="background:#2E7E9E"></div>
      <div class="block-alloc-label">Fixed Income</div>
      <div class="block-alloc-pct">${block.fixedIncome.toFixed(2)}%</div>
    </div>
    <div class="block-alloc-row">
      <div class="block-alloc-dot" style="background:#6B5B95"></div>
      <div class="block-alloc-label">Alt Assets</div>
      <div class="block-alloc-pct">${block.altAssets.toFixed(2)}%</div>
    </div>
  </div>
</div>`
    }

    case 'watchlist': {
      const rows = block.items.map(item => {
        const logoUri = getLogoUri(item.ticker)
        const chgClass = item.gain ? 'gain' : 'loss'
        return `<div class="block-watchlist-row">
  <img src="${logoUri}" class="block-watchlist-logo" alt="${escapeHtml(item.ticker)}"/>
  <div class="block-watchlist-ticker">${escapeHtml(item.ticker)}</div>
  <div class="block-watchlist-price">${escapeHtml(item.price)}</div>
  <div class="block-watchlist-chg ${chgClass}">${escapeHtml(item.change)}</div>
</div>`
      }).join('\n')
      return `<div class="block-watchlist" style="${mb}">
  <div class="block-watchlist-header">
    <span class="block-watchlist-title">${escapeHtml(block.title)}</span>
  </div>
  ${rows}
</div>`
    }

    default:
      return ''
  }
}

const ARCHETYPE_TABS: Record<string, string[]> = {
  fintech:   ['Portfolio', 'Markets', 'Transfer', 'Invest', 'More'],
  banking:   ['Home', 'Accounts', 'Transfer', 'Cards', 'More'],
  fitness:   ['Home', 'Workout', 'Progress', 'Profile', 'More'],
  health:    ['Home', 'Vitals', 'Activity', 'Profile', 'More'],
  social:    ['Home', 'Explore', 'Post', 'Notifications', 'Profile'],
  ecommerce: ['Home', 'Search', 'Cart', 'Orders', 'Profile'],
  dashboard: ['Dashboard', 'Analytics', 'Reports', 'Settings', 'Profile'],
  default:   ['Home', 'Explore', 'Activity', 'Profile', 'More'],
}

const LUCIDE_HTML_SVGS: Record<string, string> = {
  Portfolio:     `<rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/>`,
  Markets:       `<polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/>`,
  Transfer:      `<polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/>`,
  Invest:        `<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>`,
  More:          `<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>`,
  Home:          `<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>`,
  Accounts:      `<rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/>`,
  Cards:         `<rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/>`,
  Workout:       `<path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/><line x1="6" y1="1" x2="6" y2="4"/><line x1="10" y1="1" x2="10" y2="4"/><line x1="14" y1="1" x2="14" y2="4"/>`,
  Progress:      `<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>`,
  Profile:       `<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>`,
  Vitals:        `<polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>`,
  Activity:      `<polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>`,
  Explore:       `<circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/>`,
  Post:          `<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/>`,
  Notifications: `<path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/>`,
  Search:        `<circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>`,
  Cart:          `<circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/>`,
  Orders:        `<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/>`,
  Dashboard:     `<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>`,
  Analytics:     `<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>`,
  Reports:       `<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>`,
  Settings:      `<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>`,
}

function renderTabBar(appType?: string): string {
  const key = (appType ?? 'default').toLowerCase()
  const tabs = ARCHETYPE_TABS[key] ?? ARCHETYPE_TABS['default']
  const items = tabs.map((label, i) => {
    const isActive = i === 0
    const iconPaths = LUCIDE_HTML_SVGS[label] ?? LUCIDE_HTML_SVGS['Activity']
    const color = isActive ? 'var(--jazz-primary)' : 'var(--jazz-muted)'
    return `<button class="tab-item${isActive ? ' active' : ''}">
  <svg viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${iconPaths}</svg>
  <span class="tab-item-label">${escapeHtml(label)}</span>
</button>`
  }).join('\n')
  return `<div class="tab-bar">\n${items}\n</div>`
}

function resolvePadding(padding: number | { top?: number; right?: number; bottom?: number; left?: number } | undefined): string {
  const MIN = 16
  if (padding === undefined) return `${MIN}px`
  if (typeof padding === 'number') {
    const p = Math.max(padding, MIN)
    return `${p}px`
  }
  const t = Math.max(padding.top ?? MIN, MIN)
  const r = Math.max(padding.right ?? MIN, MIN)
  const b = Math.max(padding.bottom ?? MIN, MIN)
  const l = Math.max(padding.left ?? MIN, MIN)
  return `${t}px ${r}px ${b}px ${l}px`
}

export function renderToHtml(spec: DesignSpecV1, useWireframe = false): string {
  const title = spec.meta?.title ?? 'FiFi Prototype'
  const screens = spec.screens ?? []
  const total = screens.length

  // Handoff card metadata
  const userRequest = spec.meta?.userRequest ?? ''
  const promptDisplay = userRequest.length > 120
    ? userRequest.slice(0, 117) + '…'
    : userRequest
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })

  const appType = spec.meta?.intent?.appType ?? 'default'
  const tabBarHtml = renderTabBar(appType)

  const screenHtml = screens.map((screen, i) => {
    const gap = Math.max(screen.layout?.gap ?? 16, 12)
    const paddingCss = resolvePadding(screen.layout?.padding)
    const allBlocks = screen.blocks ?? []
    const bodyBlocks = allBlocks.filter(b => b.type !== 'button')
    const actionBlocks = allBlocks.filter(b => b.type === 'button')

    const bodyHtml = bodyBlocks.map(b => renderBlock(b, gap)).join('\n    ')
    const actionsHtml = actionBlocks.length > 0
      ? `\n<div class="screen-actions">\n  ${actionBlocks.map(b => renderBlock(b, 0)).join('\n  ')}\n</div>`
      : ''
    const activeClass = i === 0 ? ' active' : ''

    return `<div class="screen-wrapper${activeClass}" data-screen="${i}">
  <div class="screen-title-bar">${escapeHtml(screen.name)}</div>
  <div class="screen-content" style="padding:${paddingCss}">
    ${bodyHtml}
  </div>${actionsHtml}
</div>`
  }).join('\n')

  const dotsHtml = screens.map((_, i) =>
    `<button class="nav-dot${i === 0 ? ' active' : ''}" onclick="goToScreen(${i})" aria-label="Screen ${i + 1}"></button>`
  ).join('\n      ')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  ${!useWireframe && FONT_FACE_CSS ? `<style>${FONT_FACE_CSS}</style>` : ''}
  <style>
    :root { ${useWireframe ? WIREFRAME_CSS_VARS.trim() : JAZZ_CSS_VARS.trim()} }
    ${BASE_CSS.trim()}
    ${PANEL_CSS.trim()}
    ${useWireframe ? WIREFRAME_OVERRIDE_CSS.trim() : ''}
  </style>
</head>
<body${useWireframe ? ' class="wireframe"' : ''}>

  <div class="handoff-card" role="banner" aria-label="Design handoff summary">
    <div class="handoff-card-top">
      <span class="handoff-card-title">${escapeHtml(title)}</span>
      <div class="handoff-card-badges">
        <span class="handoff-badge handoff-badge--source">FigmAI Design Workshop</span>
        <span class="handoff-badge handoff-badge--ds">${useWireframe ? 'Wireframe' : 'Jazz DS'}</span>
        <span class="handoff-badge handoff-badge--screens">${total} screen${total !== 1 ? 's' : ''}</span>
        <span class="handoff-badge handoff-badge--date">${escapeHtml(dateStr)}</span>
      </div>
    </div>
    ${promptDisplay ? `<div class="handoff-card-prompt">"${escapeHtml(promptDisplay)}"</div>` : ''}
  </div>

  <div class="proto-workspace">
    <div class="proto-left">
      <div class="phone-frame">
        <div class="status-bar">
          <span class="status-bar-time">9:41</span>
          <div class="status-bar-icons">
            <span>●●●</span>
            <span>WiFi</span>
            <span>🔋</span>
          </div>
        </div>
        ${screenHtml}
        ${tabBarHtml}
      </div>

      <nav class="proto-nav" aria-label="Screen navigation">
        <div class="nav-dots">
          ${dotsHtml}
        </div>
        <div class="nav-arrows">
          <button class="nav-arrow-btn" id="nav-back" onclick="goToScreen(currentScreen - 1)">← Back</button>
          <span class="nav-screen-counter" id="nav-counter">1 / ${total}</span>
          <button class="nav-arrow-btn" id="nav-next" onclick="goToScreen(currentScreen + 1)">Next →</button>
        </div>
      </nav>
    </div>

    ${PANEL_HTML}
  </div>

  <div class="cs-toast" id="cs-toast"></div>

  <script>${PROTOTYPE_JS}${PANEL_JS}</script>
</body>
</html>`
}
